# action.yml
name: 'Image Resizer Inplace with Limits'
description: 'In place resize images inside a folder when over a certain size limit'
branding:
  icon: 'image'  
  color: 'green'
inputs:
  target:
    description: 'Folder in which images are stored'
    required: true
    default: 'images'
  dimensions:
    description: 'New resolution for images'
    required: true
    default: '70%'
  widthLimit:
    description: 'Width Limit'
    required: true
  heightLimit:
    description: 'Height Limit'
    required: true
outputs:
  images_changed:
    description: 'A string listing all images resized'
  csv_images_changed:
    description: 'A csv listing all images resized'
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.widthLimit }}
    - ${{ inputs.heightLimit }}
    - ${{ inputs.target }}
    - ${{ inputs.dimensions }}
    
